apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      serviceAccountName: cloud-sql-proxy-sa
      containers:
      - name: sample-app
        image: europe-west2-docker.pkg.dev/microservice-on-kubernetes/sample-app-repo/gcprestfulmicroservicekubernetes:latest06
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_pass
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db_name
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
        args:
        - "--structured-logs"
        - "--port=3306"
        - "microservice-on-kubernetes:europe-west2:sampleapp-db"
        securityContext:
          runAsNonRoot: true